- import_playbook: plays/distribute_ssh_keys.yaml
- import_playbook: plays/configure_hostnames.yaml
- import_playbook: plays/add_host_entries.yaml
- import_playbook: plays/generate_tls_certs.yaml
- import_playbook: plays/distribute_tls_certs.yaml
- import_playbook: plays/generate_kubeconfig_auth.yaml
- import_playbook: plays/distribute_kubeconfig_auth.yaml
- import_playbook: plays/distribute_kubeconfig_auth.yaml
- import_playbook: plays/generate_encryption_key.yaml
- import_playbook: plays/bootstrap_etcd_cluster.yaml
- import_playbook: plays/bootstrap_control_plane.yaml
- import_playbook: plays/bootstrap_worker_nodes.yaml