certs:
  - admin
  - node-0
  - node-1
  - kube-proxy
  - kube-scheduler
  - kube-controller-manager
  - kube-api-server
  - service-accounts
cert_dir: /var/lib/kubelet/
cert_dir_remote: /etc/kubernetes/pki

