- name: Ensure certificate directory exists
  file:
    path: "{{ cert_dir }}"
    state: directory
    mode: '0755'

- name: Generate the Root RSA private key
  ansible.builtin.command:
    cmd: openssl genrsa -out ca.key 4096
    chdir: "{{ cert_dir }}"

- name: Generate the Root Certificate
  ansible.builtin.command:
    cmd: openssl req -x509 -new -sha512 -noenc -key ca.key -days 3653 -config ca.conf -out ca.crt
    chdir: "{{ cert_dir }}"

# - name: Generate a RSA key for each Kubernetes component
#   ansible.builtin.command:
#     cmd: "openssl genrsa -out {{ item }}.key 4096"
#     chdir: "{{ cert_dir }}"
#   loop: "{{ certs }}"
#   loop_control:
#     label: "{{ item }}.key"