- name: Generate an RSA private key
  ansible.builtin.command:
    cmd: openssl genrsa -out ca.key 4096
    chdir: "{{ cert_dir }}"

- name: List ,crt, key and csr files
  ansible.builtin.command:
    cmd: ls -1 *.crt *.key *.csr
    chdir: "{{ cert_dir }}"
    register: directory_contents

- name: Display directory contents
  debug:
    var: directory_contents.stdout_lines