- name: Ensure certificate directory exists
  file:
    path: "{{ cert_dir }}"
    state: directory
    mode: '0755'

- name: Generate an RSA private key
  ansible.builtin.command:
    cmd: openssl genrsa -out ca.key 4096
    chdir: "{{ cert_dir }}"

- name: Find all generated .crt, .key, and .csr files
  ansible.builtin.find:
    paths: "{{ cert_dir }}"
    patterns: "*.crt,*.key,*.csr"
  register: cert_files

- name: Show generated .crt, .key, and .csr files
  ansible.builtin.debug:
    msg: "{{ item.filename }}"
  loop: "{{ cert_files.files }}"
  when: item.filename is defined