- name: Ensure certificate directory exists
  file:
    path: "{{ cert_dir }}"
    state: directory
    mode: '0755'

- name: Generate an RSA private key
  ansible.builtin.command:
    cmd: openssl genrsa -out ca.key 4096
    chdir: "{{ cert_dir }}"

- name: Generate a Root Certificate
  ansible.builtin.shell: |
    openssl req -x509 -new -sha512 -noenc
    -key ca.key -days 3653
    -config ca.conf
    -out ca.crt
  args:
    chdir: "{{ cert_dir }}"
