- name: Create Host Lookup Table
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} Kubernetes The Hard Way"
    block: "{{ lookup('template', 'hosts_entries.j2') }}"
    create: yes

- name: Get Hostname of machines from the cluster and display it
  ansible.builtin.shell: "hostname"
  register: hostname_entry_results
  changed_when: false

- name: Display Hostname of machine
  ansible.builtin.debug:
    msg: "FQDN is {{ ansible_hostname_entry }}"