- name: Create Host Lookup Table
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} Kubernetes The Hard Way"
    block: "{{ lookup('template', 'hosts_entries.j2') }}"
    create: yes
