- name: Create Host Lookup Table
  ansible.builtin.copy:
    content: |
      # Kubernetes The Hard Way
    dest: "/etc/hosts"
    mode: '0644'
  delegate_to: "{{ hostvars[host]['inventory_hostname'] }}"
