server_certs:
  - ca.crt
  - ca.key
  - kube-api-server.crt
  - kube-api-server.key
  - service-accounts.crt
  - service-accounts.key
cert_dir_local: /etc/kubernetes/pki
cert_dir_remote: /var/lib/kubelet
