- name: Generate kubeconfig files for worker nodes
  import_tasks: generate_kubeconfig_workers.yaml

- name: Generate kubeconfig files for the kube-proxy service
  import_tasks: generate_kubeconfig_proxy.yaml