- name: Set Cluster Entry
  ansible.builtin.shell: >
    kubectl config set-cluster {{ cluster_name }}
    --certificate-authority=ca.crt
    --embed-certs=true
    --server={{ server_url }}:{{ server_port }}
    --kubeconfig={{ item }}.kubeconfig
  args:
    chdir: "{{ work_dir }}"
  loop: "{{ nodes }}"
  loop_control:
    label: "{{ item }}.kubeconfig"

- name: CHMOD 644 all RSA keys
  ansible.builtin.command: chmod 644 {{ item }}.kubeconfig
  args:
    chdir: "{{ cert_dir }}"
  loop: "{{ nodes }}"
  loop_control:
    label: "{{ item }}.kubeconfig"

- name: Set credentials
  ansible.builtin.shell: >
    kubectl config set-credentials system:node:{{ item }}
    --client-certificate={{ item }}.crt
    --client-key={{ item }}.key
    --embed-certs=true
    --kubeconfig={{ item }}.kubeconfig
  args:
    chdir: "{{ work_dir }}"
  loop: "{{ nodes }}"
  loop_control:
    label: "{{ item }}.kubeconfig"

- name: Set Default Context
  ansible.builtin.shell: >
    kubectl config set-context default
    --cluster={{ cluster_name }}
    --user=system:node:{{ item }}
    --kubeconfig={{ item }}.kubeconfig
  args:
    chdir: "{{ work_dir }}"
  loop: "{{ nodes }}"
  loop_control:
    label: "{{ item }}.kubeconfig"

- name: Use Default Context
  ansible.builtin.command: kubectl config use-context default --kubeconfig={{ item }}.kubeconfig
  args:
    chdir: "{{ work_dir }}"
  loop: "{{ nodes }}"
  loop_control:
    label: "{{ item }}.kubeconfig"