- name: Generate Kubeconfig files for worker nodes
  ansible.builtin.shell: >
    kubectl config set-cluster {{ cluster_name }}
    --certificate-authority=ca.crt
    --embed-certs=true
    --server={{ server_url }}:{{ server_port }}
    --kubeconfig={{ hostvars[inventory_hostname]['hostname'] }}.kubeconfig
  args:
    chdir: "{{ work_dir }}"
  delegate_to: localhost
  when: "'node' in hostvars[inventory_hostname]['hostname']"