- name: Ensure SSH key pair exists on control node
  delegate_to: localhost
  ansible.builtin.command: >
    ssh-keygen -t rsa -b 4096 -f "{{ ssh_key_path }}"
    -N ""
  args:
    creates: "{{ ssh_key_path }}"

- name: Display SSH key paths
  ansible.builtin.debug:
    msg: "SSH Key Path: {{ ssh_key_path }}, SSH Public Key Path: {{ ssh_public_key_path }}"

- name: Authorize SSH key on remote nodes
  ansible.builtin.authorized_key:
    user: "{{ ssh_target_user }}"
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
