- name: Ensure SSH key pair exists on control node
  delegate_to: localhost
  ansible.builtin.command: >
    ssh-keygen -t rsa -b 4096 -f "{{ ssh_key_path }}"
    -N ""
  args:
    creates: "{{ ssh_key_path }}"

- name: Ensure public key file exists
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ ssh_public_key_path }}"
  register: key_file

- name: Fail if public key doesn't exist
  ansible.builtin.fail:
    msg: "Public key file not found!"
  when: not key_file.stat.exists

- name: Fetch public key from localhost
  delegate_to: localhost
  ansible.builtin.slurp:
    src: "{{ ssh_public_key_path }}"
  register: pubkey

- name: Authorize SSH key on remote nodes
  ansible.builtin.authorized_key:
    user: "{{ ssh_target_user }}"
    key: "{{ pubkey['content'] | b64decode }}"
