- name: Generate TLS certificates on localhost
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  roles:
    - role: generate_tls_certificates
      tags: [generate_tls_certs]