- name: Generate TLS certificates on localhost
  hosts: cluster
  become: true
  connection: local
  gather_facts: false
  roles:
    - role: generate_encryption_key
      tags: [generate_encryption_key]