- name: Ensure /var/lib/kubelet exists on nodes
  ansible.builtin.file:
    path: /var/lib/kubelet
    state: directory
    mode: '0755'

- name: Copy CA cert to all nodes
  ansible.builtin.copy:
    src: "{{ cert_dir }}/ca.crt"
    dest: /var/lib/kubelet/ca.crt
    mode: '0644'

- name: Copy kubelet certs to node-0
  when: inventory_hostname == "192.168.1.202"
  ansible.builtin.copy:
    src: "{{ cert_dir }}/node-0.{{ item }}"
    dest: "/var/lib/kubelet/kubelet.{{ item }}"
    mode: '0600'
  loop: ["crt", "key"]

- name: Copy kubelet certs to node-1
  when: inventory_hostname == "192.168.1.203"
  ansible.builtin.copy:
    src: "{{ cert_dir }}/node-1.{{ item }}"
    dest: "/var/lib/kubelet/kubelet.{{ item }}"
    mode: '0600'
  loop: ["crt", "key"]

- name: Copy control plane certs to server
  when: inventory_hostname == "192.168.1.201"
  ansible.builtin.copy:
    src: "{{ cert_dir }}/{{ item }}"
    dest: "~/{{ item }}"
    mode: '0600'
  loop:
    - ca.crt
    - ca.key
    - kube-api-server.crt
    - kube-api-server.key
    - service-accounts.crt
    - service-accounts.key
