- name: Ensure /var/lib/kubelet exists on nodes
  ansible.builtin.file:
    path: /var/lib/kubelet
    state: directory
    mode: '0755'
  loop: "{{ groups['cluster'] }}"
  delegate_to: "{{ item.fqdn }}"

- name: Copy CA cert to all nodes
  ansible.builtin.copy:
    src: "{{ cert_dir }}/ca.crt"
    dest: /var/lib/kubelet/ca.crt
    mode: '0644'
  loop: "{{ groups['cluster'] }}"
  delegate_to: "{{ item.fqdn }}"

- name: Copy kubelet certs to nodes dynamically
  ansible.builtin.copy:
    src: "{{ cert_dir }}/{{ inventory_hostname }}.{{ item }}"
    dest: "/var/lib/kubelet/kubelet.{{ item }}"
    mode: '0600'
  loop: ["crt", "key"]
  when: "'node' in inventory_hostname"
  delegate_to: "{{ inventory_hostname }}"

- name: Copy control plane certs to server
  ansible.builtin.copy:
    src: "{{ cert_dir }}/{{ item }}"
    dest: "/etc/kubernetes/pki/{{ item }}"
    mode: '0600'
  loop:
    - ca.crt
    - ca.key
    - kube-api-server.crt
    - kube-api-server.key
    - service-accounts.crt
    - service-accounts.key
  when: "'server' in inventory_hostname"
  delegate_to: "{{ inventory_hostname }}"
