- name: Ensure /var/lib/kubelet exists on worker nodes
  ansible.builtin.file:
    path: /var/lib/kubelet
    state: directory
    mode: '0755'
  when: "'node' in ansible_hostname"

- name: Copy CA cert to all nodes
  ansible.builtin.copy:
    src: "{{ cert_dir }}/ca.crt"
    dest: /var/lib/kubelet/ca.crt
    mode: '0644'
  when: "'node' in ansible_hostname"

- name: Copy kubelet certs to worker nodes
  ansible.builtin.copy:
    src: "{{ cert_dir }}/{{ ansible_hostname }}.{{ item }}"
    dest: "/var/lib/kubelet/kubelet.{{ item }}"
    mode: '0600'
  loop: ["crt", "key"]
  when: "'node' in ansible_hostname"

- name: Copy control plane certs to server node
  ansible.builtin.copy:
    src: "{{ cert_dir }}/{{ item }}"
    dest: "~/{{ item }}"
    mode: '0600'
  loop:
    - ca.crt
    - ca.key
    - kube-api-server.crt
    - kube-api-server.key
    - service-accounts.crt
    - service-accounts.key
  when: "'server' in ansible_hostname"
