- name: Ensure /var/lib/kubelet exists on worker nodes
  ansible.builtin.file:
    path: "{{ cert_dir }}"
    state: directory
    mode: '0755'
  when: "'node' in hostvars[inventory_hostname]['hostname']"

- name: Copy ca.crt to remote worker nodes
  ansible.builtin.copy:
    src: "{{ cert_dir_remote }}/ca.crt"  # The path on localhost
    dest: /var/lib/kubelet/ca.crt       # The path on the remote worker node
    owner: root
    group: root
    mode: '0644'
  delegate_to: localhost
  when: "'node' in hostvars[inventory_hostname]['hostname']"