- name: Ensure /var/lib/kubelet exists on worker nodes
  ansible.builtin.file:
    path: /var/lib/kubelet
    state: directory
    mode: '0755'
  when: ansible_hostname != 'server'

- name: Copy CA cert to all nodes
  ansible.builtin.copy:
    src: "{{ cert_dir }}/ca.crt"
    dest: "{{ cert_dir }}/ca.crt"
    mode: '0644'
  when: ansible_hostname != 'server'