- name: Ensure /var/lib/kubelet exists on worker nodes
  ansible.builtin.file:
    path: "{{ cert_dir }}"
    state: directory
    mode: '0755'
  when: "'node' in hostvars[inventory_hostname]['hostname']"

- name: Copy Certificate to worker nodes
  ansible.builtin.copy:
    src: "{{ cert_dir }}/ca.crt"
    dest: "{{ cert_dir_remote }}/ca.crt"
  when: "'node' in hostvars[inventory_hostname]['hostname']"
  delegate_to: localhost
