- name: Ensure /var/lib/kubelet exists on worker nodes
  ansible.builtin.file:
    path: /var/lib/kubelet
    state: directory
    mode: '0755'
  when: "'node' in ansible_hostname"

- name: Copy CA cert to worker nodes
  ansible.builtin.copy:
    src: "{{ cert_dir }}/ca.crt"
    dest: "{{ cert_dir }}/ca.crt"
    mode: '0644'
  when: "'node' in ansible_hostname"

- name: Copy kubelet certs to worker nodes
  ansible.builtin.copy:
    src: "{{ cert_dir }}/{{ ansible_hostname }}.{{ item }}"
    dest: "{{ cert_dir }}/kubelet.{{ item }}"
    mode: '0600'
  loop: ["crt", "key"]
  when: "'node' in ansible_hostname"

- name: Copy control plane certs to server node
  ansible.builtin.copy:
    src: "{{ cert_dir }}/{{ item }}"
    dest: "~/{{ item }}"
    mode: '0600'
  loop: "{{ server_certs }}"
  when: "'server' in ansible_hostname"
