- name: Ensure /var/lib/kubelet exists on worker nodes
  ansible.builtin.file:
    path: "{{ cert_dir_remote }}"
    state: directory
    mode: '0755'
  when: "'node' in hostvars[inventory_hostname]['hostname']"

- name: Copy Root Certificate to remote worker nodes
  ansible.builtin.copy:
    src: "{{ cert_dir_local }}/ca.crt"
    dest: "{{ cert_dir_remote }}/ca.crt"
  when: "'node' in hostvars[inventory_hostname]['hostname']"

- name: Copy Certificate to remote worker nodes
  ansible.builtin.copy:
    src: "{{ cert_dir_local }}/{{ hostvars[inventory_hostname]['hostname'] }}.crt"
    dest: "{{ cert_dir_remote }}/kubelet.crt"
  when: "'node' in hostvars[inventory_hostname]['hostname']"

- name: Copy RSA Key to remote worker nodes
  ansible.builtin.copy:
    src: "{{ cert_dir_local }}/{{ hostvars[inventory_hostname]['hostname'] }}.key"
    dest: "{{ cert_dir_remote }}/kubelet.key"
    mode: '0600'
  when: "'node' in hostvars[inventory_hostname]['hostname']"


- name: Copy Certificates and Private Keys to Server
  ansible.builtin.copy:
    src: "{{ cert_dir_local }}/{{ item }}"
    dest: "~/"
    mode: '0600'
  loop: "{{ server_certs }}"
  when: "'server' in hostvars[inventory_hostname]['hostname']"