- name: Ensure /var/lib/kubelet exists on worker nodes
  ansible.builtin.file:
    path: "{{ cert_dir }}"
    state: directory
    mode: '0755'
  when: "'node' in hostvars[inventory_hostname]['hostname']"

- name: Copy ca.crt to remote worker nodes
  ansible.builtin.synchronize:
    src: "{{ cert_dir_remote }}/ca.crt"
    dest: "{{ cert_dir }}/ca.crt"
    mode: push
    transport: scp
  delegate_to: localhost
  when: "'node' in hostvars[inventory_hostname]['hostname']"