- name: Ensure /var/lib/kubelet exists on worker nodes
  ansible.builtin.file:
    path: "{{ cert_dir }}"
    state: directory
    mode: '0755'
  when: "'node' in hostvars[inventory_hostname]['hostname']"

- name: Copy ca.crt to remote worker nodes
  ansible.posix.synchronize:
    src: "{{ cert_dir_local }}/ca.crt"  # This is on the control node
    dest: "{{ cert_dir_remote }}/ca.crt"  # This is on the managed nodes
    mode: push
  delegate_to: localhost
  become: true
  when: "'node' in hostvars[inventory_hostname]['hostname']"