- name: Ensure /var/lib/kubelet exists on worker nodes
  ansible.builtin.file:
    path: "{{ cert_dir_remote }}"
    state: directory
    mode: '0755'
  when: "'node' in hostvars[inventory_hostname]['hostname']"

- name: Copy ca.crt to remote worker nodes
  ansible.builtin.copy:
    src: "{{ cert_dir_local }}/ca.crt"  # This is on the control node
    dest: "{{ cert_dir_remote }}/ca.crt"  # This is on the managed nodes
    mode: '0644'  # File permissions
  become: true  # Use sudo privileges to write to the remote directory
  when: "'node' in hostvars[inventory_hostname]['hostname']"