- name: Ensure /var/lib/kubelet exists on worker nodes
  ansible.builtin.file:
    path: /var/lib/kubelet
    state: directory
    mode: '0755'
  when: "'node' in (hostvars[inventory_hostname]['hostname'] | default(''))"

